/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import javafx.application.Application;

public class App  {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) {
        Application.launch(Aplicacion.class, args);
    }
}
