package logica;

public class Diccionario {
    public String[] nombres;
    public String[] apellidos;

    public Diccionario() {
        this.apellidos = new String[] { "Acosta", "Acuña", "Aguilar", "Aguirre", "Agustín", "Ahumada", "Alanis",
                "Alarcón", "Alayón", "Alcázar", "Alcocer", "Alfaro", "Almendárez", "Altamirano", "Álvarez", "Alzate",
                "Amador", "Anaya", "Argüelles", "Arjona", "Arriaga", "Arrollo", "Ayala", "Baca", "Báez", "Baños",
                "Barba", "Barrera", "Barrientos", "Barriga", "Bastida", "Batalla", "Bautista", "Bazán", "Becerra",
                "Becerril", "Bello", "Beltrán", "Benítez", "Bernal", "Bolaños", "Bonilla", "Borges", "Bustamante",
                "Busto", "Caballero", "Cabeza", "Cabrera", "Cadenas", "Caldera", "Calleja", "Calles", "Camacho",
                "Camareno", "Camarillo", "Campos", "Cárdenas", "Cardoso", "Carranza", "Carrillo", "Carvajal",
                "Carvallo", "Casas", "Castellanos ", "Castañeda", "Cepeda", "Cerda", "Cervantes", "Céspedes",
                "Cevallos", "Cevedo", "Chávez", "Chavira", "Cisneros", "Collado", "Cordero", "Cornejo", "Correa",
                "Corro", "Cuéllar", "Cuervo", "Cuesta", "Cuevas", "Daniel", "Darío", "Dávila", "De Aguilar", "De Alba",
                "De la Cruz", "De la Cuesta", "De la Fuente", "De la Rosa", "Del Castillo", "Doblado", "Domínguez",
                "Donato", "Dorado", "Duarte", "Dueñas", "Echeverría", "Elizondo", "Enríquez", "Escalante", "Escamilla",
                "Escobar", "Escobedo", "Escoto", "Escovar", "Espino", "Esquivel", "Estévez", "Estrada", "Estrella",
                "Fábregas", "Falcón", "Farías", "Fernández", "Ferreira", "Ferrer", "Fierro", "Figueras", "Flores",
                "Fonseca", "Fraga", "Frías", "Fuentes", "Funez", "Gaitán", "Galán", "Galeano", "Galeno", "Galindo",
                "Gallegos", "Galván", "Gamboa", "Gámez", "García", "Garrido", "Gavilán", "Gayoso", "Gaytán", "Gillén",
                "Godines", "Gómez", "Góngora", "Granada", "Granados", "Grijalba", "Guardado", "Guardiola", "Guerrero",
                "Guillén", "Gutiérrez", "Guzmán", "Heredia", "Hernández", "Herrera", "Hidalgo", "Hierro", "Huerta",
                "Hurtado", "Ibáñez", "Ibarra", "Icaza", "Iglesias", "Infante", "Ivañez", "Izquierdo", "Jara",
                "Jaramillo", "Jerano", "Jiménez", "Juárez", "Junco", "Jurado", "Lacayo", "Lafuente", "Lagos", "Lagunal",
                "Lamas", "Lández", "Larios", "Lastreto", "Lázaro", "Leandro", "Lemus", "Leyva", "Linares", "Lines",
                "Lira", "Lizano", "Llano", "Lobo", "Lombardo", "López", "Loredo", "Lorio", "Losada", "Lozano", "Lucas",
                "Lugo", "Luna", "Macedo", "Machado", "Macías", "Maduro", "Magallón", "Maldonado", "Maltés", "Mantilla",
                "Manuel", "Manzanal", "Manzano", "Marcías", "Marrero", "Marroquí", "Martí", "Martínez", "Mateo",
                "Matías", "Maurer", "Medrano", "Medina", "Mendoza", "Mejía", "Mena", "Meneses", "Merazo", "Meza",
                "Mijares", "Milanés", "Minas", "Molina", "Molleda", "Moneda", "Monge", "Montalbán", "Montalvo",
                "Montecinos", "Montero", "Montes", "Montiel", "Morillo", "Moscoa", "Munera", "Murillo", "Naranjo",
                "Navaro", "Navarrete", "Navarro", "Nieto", "Noble", "Noguera", "Noriega", "Novales", "Novo", "Novoa",
                "Núñez", "Obellón", "Obregón", "Ocampo", "Ochoa", "Ordóñez", "Olguín", "Olivar", "Olivares", "Olivera",
                "Olmeda", "Olmedo", "Olmo", "Ordóñez", "Orozco", "Ortega", "Ortiz", "Oseda", "Osorio", "Ospino",
                "Otero", "Oviedo", "Ozuno ", "Pacheco", "Padilla", "Páez", "Palacio", "Paladino", "Palazuelos",
                "Palomar", "Palomino ", "Paniagua", "Pantoja", "Parado", "Páramo", "Pardo", "Paredes", "Parra",
                "Pastor", "Pastrana", "Patiño", "Paz", "Pedroza", "Pena", "Peña", "Peralta", "Peraza", "Perdomo",
                "Pineda", "Pino", "Plácido", "Ponce", "Portillo", "Prada", "Prieto", "Puente", "Quesada", "Quevedo",
                "Quijada", "Quijano", "Quintana", "Quintanilla", "Quiroga", "Quiroz", "Ramírez", "Ramón", "Ramos",
                "Rangel", "Real", "Redondo", "Restrepo", "Reyes", "Rivas", "Rivera", "Roble", "Robles", "Rojas",
                "Roldán", "Román", "Romero", "Rosales", "Rosas", "Rovira", "Rubín", "Rubio", "Rueda", "Ruiz", "Sabín",
                "Sáenz", "Sagel", "Sala", "Salas", "Salazar", "Salcedo", "Saldaña", "Saldivar", "Salinas", "Salmón",
                "Salvado", "Samper", "Sánchez", "Sandino", "Sandoval", "Santiago", "Santos", "Sardinas", "Sarmiento",
                "Saucedo", "Savala", "Seballos", "Sedano", "Segura", "Silva", "Sol", "Solana", "Solé", "Soler", "Solís",
                "Somoza", "Sorio", "Sotelo", "Soto", "Sotomayor", "Soza", "Suárez", "Tablada", "Talavera", "Tames",
                "Taracena", "Tedesco", "Tejada", "Tobar", "Torre", "Torrente", "Tovar", "Travieso", "Trejos",
                "Treminio", "Triguero", "Troncoso", "Trujillo", "Ulloa", "Ureña", "Uriarte", "Uribe", "Urieta",
                "Urrutia", "Usaga", "Uveda" };
        this.nombres = new String[] { "Aarón", "Ander", "Joaquín", "Abel", "Andrés", "Joel", "Abelardo", "Ángel", "Jon",
                "Abraham", "Aníbal", "Jordi", "Adalberto", "Antonio", "Jorge", "Adam", "Arnau", "José", "Adán",
                "Arturo", "Jose", "Antonio", "Adiran", "Asier", "Jose", "Luis", "Adolfo", "Augusto", "Jose", "Manuel",
                "Adrià", "Aurelio", "Jose", "Maria", "Adrián", "Baltasar", "Juan", "Agustín", "Bartolomé", "Blas",
                "Aimar", "Basilio", "Juan", "Antonio", "Aitor", "Benito", "Boris", "Alano", "Benjamín", "Juan",
                "Carlos", "Alberto", "Bernardo", "Borja", "Aldo", "Bienvenido", "Brahim", "Aleix", "Blas", "Brais",
                "Alejandro", "Boris", "Bruno", "Alejo", "Borja", "Calisto", "Alex", "Brahim", "Juan", "José", "Alfonso",
                "Brais", "Camilo", "Alfredo", "Bruno", "Juan", "Manuel", "Alonso", "Calisto", "Carlos", "Álvaro",
                "Camilo", "Julio", "Amadeo", "Carlos", "Cayetano", "Amado", "Cayetano", "César", "Amando", "César",
                "Christian", "Ambrosio", "Christian", "Claudio", "Amin", "Claudio", "Clemente", "Anastasio", "Clemente",
                "Conrado", "Ander", "Conrado", "Constantino", "Constantino", "Francisco", "Javier", "Joel", "Crispín",
                "Francisco", "José", "Jon", "Cristian", "Gabriel", "Jordi", "Daniel", "Gaspar", "Jorge", "Darío",
                "Gerard", "José", "David", "Gerardo", "Jose", "Antonio", "Desiderio", "Germán", "Jose", "Luis", "Diego",
                "Gonzalo", "Jose", "Manuel", "Dionisio", "Gregorio", "Jose", "Maria", "Domingo", "Guillem", "Juan",
                "Donato", "Guillermo", "Juan", "Antonio", "Edgar", "Gustavo", "Juan", "Carlos", "Edmundo", "Hamza",
                "Juan", "José", "Eduardo", "Héctor", "Juan", "Manuel", "Elías", "Honorato", "Julio", "Eloy", "Hugo",
                "Justino", "Emilio", "Humberto", "Justo", "Eneko", "Ibai", "Kevin", "Enrique", "Ibrahim", "Kilian",
                "Eric", "Ignacio", "Leo", "Ernesto", "Iker", "Leopoldo", "Esteban", "Isidoro", "Lorenzo", "Eugenio",
                "Ismael", "Louis", "Eusebio", "Ivo", "Lucas", "Fabián", "Izan", "Luciano", "Federico", "Jaime", "Luis",
                "Felipe", "Jan", "Macario", "Félix", "Jaume", "Manuel", "Fermín", "Javier", "Marc", "Fernando", "Jesús",
                "Marcelo", "Fidel", "Joan", "Marco", "Francisco", "Joaquín", "Marcos", "Marcos", "Pau", "Tomás",
                "Mariano", "Pedro", "Ulises", "Mario", "Pelayo", "Unai", "Marti", "Plácido", "Urbano", "Martín",
                "Platón", "Valentín", "Mateo", "Pol", "Vicente", "Matías", "Ponce", "Víctor", "Mauricio", "Quintín",
                "Virgilio", "Maximiliano", "Rafael", "Walter", "Máximo", "Ramiro", "Wen", "Miguel", "Ramón", "Xabier",
                "Miguel", "Ángel", "Raúl", "Xavier", "Mikel", "Ricardo", "Ximen", "Mohamed", "Roberto", "Yerai",
                "Moisés", "Rodrigo", "Yeray", "Nabil", "Rogelio", "Yunes", "Narciso", "Román", "Yusef", "Nathan",
                "Rubén", "Zacarías", "Nicolás", "Salvador", "Zenon", "Noé", "Samuel", "Zoilo", "Octavio", "Santiago",
                "Oier", "Sebastián", "Omar", "Sergi", "Oriol", "Sergio", "Óscar", "Silvestre", "Pablo", "Simón",
                "Pancho", "Teodoro" };
    }
}
